### PR TITLE
Migrate: Mellanox Onyx Ansible Collection

### PR DESCRIPTION
**Pull request by samerd**
Signed-off-by: Samer Deeb <samerd@mellanox.com>

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by samerd** [comment]
This PR merges all onyx modules from ansible to ansible-collection.
Yet, I need to set CI mechanism

**Comment by gundalow** [comment]
For CI copy lines 1-24 from https://github.com/ansible-collections/community.grafana/blob/master/.github/workflows/ansible-test.yml

Change line 13 to be `mellanox/onyx`



Is this content being moved out of another collection? If so this maybe of use https://github.com/ansible-collections/overview/blob/master/README.rst#q-what-should-i-do-to-move-plugins-across-collections-during-migration

**Comment by samerd** [comment]
Thanks so much @gundalow ,
this collection is migrated from: [community.network](https://github.com/ansible-collections/community.network), so I'll create a PR for onyx removal from community.network

**Comment by gundalow** [comment]
Thanks, and a 3rd PR to update ansible/ansible's runtime.yml (which will need backporting to the stable-2.10 branch)

**Comment by thedoubl3j** [comment]
great to see @samerd! if you need any help with the other PRs, please feel free to tag me and I will review and give a :heavy_check_mark: where appropriate.

**Comment by gundalow** [comment]
Not sure why CI hasn't been triggered. Going to close/open the PR.

**Comment by samerd** [comment]
@gundalow : I've completed all 3 PRs for migration, please review.
Thanks.

**Comment by gundalow** [comment]
@samerd Excellent, thank you.
I'm not sure why GitHub actions hasn't been run here.

Though this is your repo, so you are free to hit merge

**Comment by samerd** [comment]
Thanks,
I'll merge

**Pull request merged**
